name = "QuadropoleIonTrap"
authors = ["mmaehring"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
DrWatson = "2.5.0"
julia = "1.6.0"
